import mSequences from "./sequences";
import mUser from "./users";
import mClient from "./clients";
import mProgram from "./programs";
import mTasks from "./tasks";
import mKanbans from "./kanbans";
import mNotes from "./notes";
import mLogs from "./logs";
import mProducts from "./products";
import mOrders from "./orders";
import mChats from "./chats";
import mSchedule from "./schedule";
import mBooking from "./booking";

export const sequences = mSequences;
export const users = mUser;
export const clients = mClient;
export const programs = mProgram;
export const tasks = mTasks;
export const kanbans = mKanbans;
export const notes = mNotes;
export const logs = mLogs;
export const products = mProducts;
export const orders = mOrders;
export const chats = mChats;
export const schedule = mSchedule; 
export const bookings = mBooking; 